version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
